### ISSUE TITLE
Next JS exampple with i18n

### ISSUE THREAD

**Issue by raqibnur** [williamiommi/sanity-plugin-i18n-fields#4]
is there any Next JS example or guide with sanity-plugin-i18n-fields?

**Comment by williamiommi** [comment]
Hi, 
no sorry there is no example or guide for Nextjs.
The plugin it's not related to any particular framework. It has an identical data structure to the example found in the [Sanity documentation](https://www.sanity.io/docs/localization#597ea22e7bce).

So, if you want to query a specific locale for a specific field, I will do the following:

1. Get the current locale code from your Next js application (it should be the same as the one configured on the Sanity plugin or otherwise you need a specific 1:1 mapping)
2. Create a Groq query with a dynamic attribute for the locale.

So if we assume that your current location is 'en', the query could be like the following:

```ts
yourSanityClient.fetch(
    `*[_type == 'article'] {
        ...,
        'title': title[$locale]
    }`,
    {
        locale: 'en' // this should be a variable coming from nextjs with the current locale
    },
)
```

**Comment by raqibnur** [comment]
Thanks, it saved me a lot of time. Is there a way to query all locale data at once?

**Comment by williamiommi** [comment]
Yes, assuming no reference documents are involved, you can simply include the name of the field in your query, and you will get all the locales that contain data:

```ts
yourSanityClient.fetch(
    `*[_type == 'article'] {
        title
    }`
)
```

the output will be

```ts
title: {
  _type: 'i18n.string',
  en: 'Hello',
  it: 'Ciao',
}
```
